model_info:
  model_type: detection
  model_name: yolov8n
  weight: ./weights/yolov8n.pt
  onnx_path: yolov8n.onnx # output onnx path
  i8_onnx_path: yolov8n_i8.onnx # quantized onnx model path
  input_shape: [1,3,640,640] # input shape for model
  nc: 80 # number of classes
  num_anchors: 3

quantization_info:
  calib_data: "/home/furiosa/Warboy/Benchmark/coco/val2017" # data directory path for calibration
  num_data: 5 # number of data for calibration
  method: MIN_MAX_ASYM # calibration method

runner_info:
  conf_thres: 0.25
  iou_thres: 0.65
  input_shape: [640,640]
  class_names:
  - person
  - bicycle
  - car
  - motorcycle
  - airplane
  - bus
  - train
  - truck
  - boat
  - traffic light
  - fire hydrant
  - stop sign
  - parking meter
  - bench
  - bird
  - cat
  - dog
  - horse
  - sheep
  - cow
  - elephant
  - bear
  - zebra
  - giraffe
  - backpack
  - umbrella
  - handbag
  - tie
  - suitcase
  - frisbee
  - skis
  - snowboard
  - sports ball
  - kite
  - baseball bat
  - baseball glove
  - skateboard
  - surfboard
  - tennis racket
  - bottle
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - chair
  - couch
  - potted plant
  - bed
  - dining table
  - toilet
  - tv
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refrigerator
  - book
  - clock
  - vase
  - scissors
  - teddy bear
  - hair drier
  - toothbrush
  anchors:
    -
