application: object_detection   #
model_name: yolov8m-face
weight: ../weights/yolov9-c.pt                       # weight file path
onnx_path: yolov8m-face.onnx                  # onnx model path
onnx_i8_path: yolov8m-face_i8.onnx # quantized onnx model path

calibration_params:
  calibration_method: SQNR_ASYM # calibration method
  calibration_data: ../../rev_demo/output_face/_input/airport_1          # calibration data path
  num_calibration_data: 200     # number of calibration data

conf_thres: 0.25
iou_thres: 0.7
input_shape: [640, 640]         # model input shape (Height, Width)
anchors:                        # anchor information
  -
class_names:
  - face