[tool.black]
skip-string-normalization = true
line-length = 100
target-versions = ["py38", "py39", "py310", "py311"]

[tool.isort]
force_sort_within_sections = true
line_length = 100
profile = "black"
